### ISSUE TITLE
Factory Translation for Collections

### ISSUE THREAD

**Issue by geoffreywiseman** [geoffreywiseman/Moo#101]
When translating a collection, you might want to use a factory to determine the class to be instantiated for the items within the collection. I don't think Moo currently allows that but it would be useful with translating a collection containing parallel hierarchies.

This isn't critical to me, but if someone else wants it, I'd consider it.

**Comment by graineri** [comment]
How feasible would be to implement this? Is there any workaround?

**Comment by geoffreywiseman** [comment]
Probably not immensely hard -- what are you trying to accomplish? You can translate items in a collection to a particular class, you just can't write a factory that dynamically chooses a class. You're trying to do the latter?

**Comment by graineri** [comment]
Exactly. 

Let's say we have a `List<Animal>` and that list can contain `Dog`s, `Cat`s and I want to translate that hierarchy into a parallel "DTO" hierarchy (i.e. `List<AnimalApi>` containing `DogApi` and `CatApi`)

**Comment by geoffreywiseman** [comment]
Yup -- that's the use case I imagined this for -- the parallel hierarchies case. Are you on the latest? I might be able to put together an update with that added.

**Comment by graineri** [comment]
Yes, exactly. I'm on the latest.

**Comment by graineri** [comment]
Thanks for considering adding this feature, Geoffrey.

Do you have an ETA?

**Comment by geoffreywiseman** [comment]
@graineri Probably not this week -- my network connection isn't reliable until next week, at which point I'll take a look and give a better estimate. PRs welcome, of course, but I don't mind doing it.

**Comment by geoffreywiseman** [comment]
Some parts of this are easy —there is already a TranslationTargetFactory interface we can use.

The biggest impediment I have found so far is the way the TranslationCache potentially instantiates the class and there’s no way of passing in a factory — so it will need some changing of the interface. Need to dig a little deeper to see the other uses.

**Comment by geoffreywiseman** [comment]
@graineri I assume you have properties in the subclasses that require translation? Without that, I already have a working prototype using `TranslationTargetFactory`, but because my test case has subclass properties, it fails.

**Comment by graineri** [comment]
@geoffreywiseman, yes, the subclasses have properties.

I have also noticed that this wasn't an easy change and that was the main reason I didn't contribute with a PR. =(

**Comment by geoffreywiseman** [comment]
I found a way through with `TranslationTargetFactory`. It doesn't strike me as the ideal way to get this change done -- and I don't love the way you have to suppress warnings on TranslationTargetFactory's generics just to make it fit, but ...  it is perhaps the minimal change that will accomplish the desired goal, and that doesn't require deeper surgery, so it might be the right fit for a point release anyway. If I make the kind of change that would make me happier with it, I'd probably have to call it Moo 3.0, and look at what else should go with it, which ... is a problem for another day, I hope.

Take a look at the [collection-factory-translation branch](https://github.com/geoffreywiseman/Moo/tree/feature/collection-factory-translation).  Look at the new test in particular to see if it matches what you had in mind.

If you can build it and test it in your context, all the better -- that would be a more complete test than a contrived JUnit scenario.

If this looks like it'll do what you want, I might apply it to Arrays and well and see if there's any other quick wins but wrap it up into a 2.1 relatively soon.

**Comment by graineri** [comment]
I thing it looks good and seems enough for what I currently need.

**Comment by geoffreywiseman** [comment]
Moo v2.1.0 is out, with collection factory translation. It's up on Maven Central, give it a try.

**Comment by geoffreywiseman** [comment]
Great! Glad to hear it. Haven't had many causes to update Moo for myself recently -- the primary project I use it on isn't even on v2.x yet, so it was nice to have a reason to do a little work on it. ;)
